"""add email column to employees table

Revision ID: 865687e3fd9b
Revises: 71cf57b593f7
Create Date: 2026-06-12 15:57:44.957157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '865687e3fd9b'
down_revision: Union[str, Sequence[str], None] = '71cf57b593f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email',sa.String(), nullable = True))
    # op.drop_table('posts')
    # op.drop_table('std')
    # op.drop_table('products')
    # op.create_foreign_key(None, 'votes', 'user2', ['post_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'votes', 'user1', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'votes', type_='foreignkey')
    # op.drop_constraint(None, 'votes', type_='foreignkey')
    # op.create_table('products',
    # sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('price ', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('is_sala', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    # sa.Column('inventory', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    # sa.Column('ceated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    # )
    # op.create_table('std',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('subject', sa.VARCHAR(), server_default=sa.text("'PCM'::character varying"), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('std_pkey'))
    # )
    # op.create_table('posts',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    # )
    
    op.drop_column('employees','email') 
    # ### end Alembic commands ###
